from frieze import *
f = Frieze('frieze_1.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_2.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_3.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_4.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_5.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_6.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
f = Frieze('frieze_7.txt')
print('hr',f.is_horizental_reflection())
print('vr',f.is_verticle_reflection())
print('ghr',f.is_glided_horizental_reflection())
print('rr',f.is_rotation())
print()
