/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define DATE_PROG ((rpc_uint)0x31234567)
#define DATE_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define BIN_DATE ((rpc_uint)1)
extern "C" long * bin_date_1(void *, CLIENT *);
extern "C" long * bin_date_1_svc(void *, struct svc_req *);
#define STR_DATE ((rpc_uint)2)
extern "C" char ** str_date_1(long *, CLIENT *);
extern "C" char ** str_date_1_svc(long *, struct svc_req *);

#elif __STDC__
#define BIN_DATE ((rpc_uint)1)
extern  long * bin_date_1(void *, CLIENT *);
extern  long * bin_date_1_svc(void *, struct svc_req *);
#define STR_DATE ((rpc_uint)2)
extern  char ** str_date_1(long *, CLIENT *);
extern  char ** str_date_1_svc(long *, struct svc_req *);

#else /* Old Style C */
#define BIN_DATE ((rpc_uint)1)
extern  long * bin_date_1();
extern  long * bin_date_1_svc();
#define STR_DATE ((rpc_uint)2)
extern  char ** str_date_1();
extern  char ** str_date_1_svc();
#endif /* Old Style C */

#endif /* !_DATE_H_RPCGEN */
